import { Model } from '../types/model';

export const MOCKED_MODELS: Model[] = [
  {
    name: 'User',
    fields: [
      {
        name: 'id',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'ID',
        description: 'A unique identifier for the user.',
        placeholder: 'Enter a unique user ID',
        defaultValue: '',
        hideInForm: true, // Hide this field in forms
      },
      {
        name: 'name',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'Name',
        description: 'The full name of the user.',
        placeholder: 'Enter the full name of the user',
        defaultValue: '',
      },
      {
        name: 'email',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'Email',
        description: 'The email address of the user.',
        placeholder: "Enter the user's email address",
        defaultValue: '',
      },
      {
        name: 'posts',
        type: { type: 'one-to-many', model: 'Post', required: false, list: true },
        required: false,
        isRelation: true,
        label: 'Posts',
        description: 'A list of posts created by the user.',
        placeholder: '',
        defaultValue: '',
      },
    ],
  },
  {
    name: 'Post',
    fields: [
      {
        name: 'id',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'ID',
        description: 'A unique identifier for the post.',
        placeholder: 'Enter a unique post ID',
        defaultValue: '',
        hideInForm: true, // Hide this field in forms
      },
      {
        name: 'title',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'Title',
        description: 'The title of the post.',
        placeholder: 'Enter the title of the post',
        defaultValue: '',
      },
      {
        name: 'content',
        type: 'String',
        required: false,
        isRelation: false,
        label: 'Content',
        description: 'The content of the post.',
        placeholder: 'Enter the content of the post',
        defaultValue: '',
      },
      {
        name: 'author',
        type: { type: 'many-to-one', model: 'User', required: true, list: false },
        required: true,
        isRelation: true,
        label: 'Author',
        description: 'The user who authored the post.',
        placeholder: '',
        defaultValue: '',
      },
      {
        name: 'comments',
        type: { type: 'one-to-many', model: 'Comment', required: false, list: true },
        required: false,
        isRelation: true,
        label: 'Comments',
        description: 'A list of comments on the post.',
        placeholder: '',
        defaultValue: '',
      },
    ],
  },
  {
    name: 'Comment',
    fields: [
      {
        name: 'id',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'ID',
        description: 'A unique identifier for the comment.',
        placeholder: 'Enter a unique comment ID',
        defaultValue: '',
        hideInForm: true, // Hide this field in forms
      },
      {
        name: 'text',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'Text',
        description: 'The text content of the comment.',
        placeholder: 'Enter the text of the comment',
        defaultValue: '',
      },
      {
        name: 'post',
        type: { type: 'many-to-one', model: 'Post', required: true, list: false },
        required: true,
        isRelation: true,
        label: 'Post',
        description: 'The post that this comment is related to.',
        placeholder: '',
        defaultValue: '',
      },
    ],
  },
  {
    name: 'Profile',
    fields: [
      {
        name: 'id',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'ID',
        description: 'A unique identifier for the profile.',
        placeholder: 'Enter a unique profile ID',
        defaultValue: '',
        hideInForm: true, // Hide this field in forms
      },
      {
        name: 'bio',
        type: 'String',
        required: false,
        isRelation: false,
        label: 'Bio',
        description: 'A short biography of the user.',
        placeholder: 'Enter a short biography',
        defaultValue: '',
      },
      {
        name: 'user',
        type: { type: 'one-to-one', model: 'User', required: true, list: false },
        required: true,
        isRelation: true,
        label: 'User',
        description: 'The user that this profile belongs to.',
        placeholder: '',
        defaultValue: '',
      },
    ],
  },
  {
    name: 'Category',
    fields: [
      {
        name: 'id',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'ID',
        description: 'A unique identifier for the category.',
        placeholder: 'Enter a unique category ID',
        defaultValue: '',
        hideInForm: true, // Hide this field in forms
      },
      {
        name: 'name',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'Name',
        description: 'The name of the category.',
        placeholder: 'Enter the category name',
        defaultValue: '',
      },
      {
        name: 'posts',
        type: { type: 'many-to-many', model: 'Post', required: false, list: true },
        required: false,
        isRelation: true,
        label: 'Posts',
        description: 'A list of posts that belong to this category.',
        placeholder: '',
        defaultValue: '',
      },
    ],
  },
  {
    name: 'Tag',
    fields: [
      {
        name: 'id',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'ID',
        description: 'A unique identifier for the tag.',
        placeholder: 'Enter a unique tag ID',
        defaultValue: '',
        hideInForm: true, // Hide this field in forms
      },
      {
        name: 'name',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'Name',
        description: 'The name of the tag.',
        placeholder: 'Enter the tag name',
        defaultValue: '',
      },
      {
        name: 'posts',
        type: { type: 'many-to-many', model: 'Post', required: false, list: true },
        required: false,
        isRelation: true,
        label: 'Posts',
        description: 'A list of posts that are tagged with this tag.',
        placeholder: '',
        defaultValue: '',
      },
    ],
  },
  {
    name: 'Like',
    fields: [
      {
        name: 'id',
        type: 'String',
        required: true,
        isRelation: false,
        label: 'ID',
        description: 'A unique identifier for the like.',
        placeholder: 'Enter a unique like ID',
        defaultValue: '',
        hideInForm: true, // Hide this field in forms
      },
      {
        name: 'user',
        type: { type: 'many-to-one', model: 'User', required: true, list: false },
        required: true,
        isRelation: true,
        label: 'User',
        description: 'The user who liked the post.',
        placeholder: '',
        defaultValue: '',
      },
      {
        name: 'post',
        type: { type: 'many-to-one', model: 'Post', required: true, list: false },
        required: true,
        isRelation: true,
        label: 'Post',
        description: 'The post that was liked.',
        placeholder: '',
        defaultValue: '',
      },
    ],
  },
];
